name: Sync github release assets with dist.ipfs.io

on: push

jobs:
  sync-github-and-dist-ipfs-io:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install execa
      - name: List github releases
        uses: actions/github-script@v5
        # if: ${{ success() }}
        with:
          script: |
            //const execa = require('execa')
            //const { stdout } = await execa('ls', ['-l'])
            //console.log(stdout)
            ;
            resp = await github.repos.listReleases({ owner: context.repo.owner, repo: context.repo.repo });
            const release_assets = [];
            for (const release of resp.data) {
              const assets = [];
              for (const asset of release.assets) {
                assets.push(asset.name);
              }
              release_assets.push({ tag: release.tag_name, assets: assets })
            }
            console.log(release_assets);
            return release_assets;
