name: Sync github release assets with dist.ipfs.io

on: push

jobs:
  sync-github-and-dist-ipfs-io:
    runs-on: "ubuntu-latest"
    steps:
      - name: List github releases
        uses: actions/github-script@v4
        # if: ${{ success() }}
        with:
          script: |
            resp = await github.repos.listReleases({ owner: context.repo.owner, repo: context.repo.repo });
            for (const release of resp.data) {
              console.log(release.tag_name, ' -> ', release.assets_url);
            }